### PR TITLE
Stealing icons from other apps for custom cmds

### PR DESCRIPTION
**Pull request by LuaTenshi**
The following should allow users to steal icons from other applications just by providing a path to their executable. 
This is however my very first commit so please be gentle.

### CODE REVIEW

**Comment by polyvertex** [comment]
To associate icons to CMDLINE items should be done automatically by Keypirinha itself. Trying to circumvent this lack of feature at plugin-level by requiring the user to configure icons manually is not the best way to go. Therefore I'm closing this even if your patch looks fine. Thanks for supporting the project!

**Comment by LuaTenshi** [comment]
I'd make it do that stuff automatically if I knew how but I don't. However I felt that it would be a nice thing to have, maybe even as a temporary work around.

**Comment by polyvertex** [comment]
As it was implied by my comment: this is beyond your reach. This part is implemented in Keypirinha itself and not exposed to the plugin API. Also, I cannot merge a temporary workaround that adds a setting to user's config file if it is to announce later this setting is obsolete.

**Comment by alexandr-san4ez** [comment]
And what if this is not a temporary solution?
Special option lets you specify the icon to force.

**Comment by polyvertex** [comment]
It would require a change in the API, so same problem than for an added setting but at API-level: the signature of the method/function would be deprecated. This has been in my bucket list for a while but it implies significant changes internally and there were always higher priorities.

Follow Keypirinha/Keypirinha#103 to get updates

**Pull request closed without merging**
