### PR TITLE
WebSearch: pre-installed sites icons

### PR DESCRIPTION
**Pull request by alexandr-san4ez**

### CODE REVIEW

**Comment by polyvertex** [comment]
Please PR on the `dev` branch

**Comment by alexandr-san4ez** [comment]
The problem is that the site icons are usually small in size and are not always on that path: `http://youtube.com/favicon.ico`.
Although you can always put it manually.

**Comment by polyvertex** [comment]
> The problem is that the site icons are usually small in size and are not always on that path ...

Actually, it is worse than that. Favicon may be referenced from different HTML tags, that may also be dynamically filled by the server-side according to client's User-Agent. Even worse, several favicons may be referenced for a single site, forcing us to download all of them to ensure we get the one with the best resolution for Keypirinha's use. Which incidentally means a Python graphic library is needed on KP's side to read the downloaded images... So yes, it is a science on its own. Maybe there's a Python library out there that just does that.

But all of this is the "ideal" solution. Perhaps a more realistic/temporary one would be a mix of both solutions:

* Allow the user, **as an option**, to install the icons themselves in the `portable\Profile\Packages\WebSearch\icons` directory
* If no favicon for the current search site is found in package's cache directory or in the `icons` directory mentioned above, then try to download the `favicon.ico` file from a hard-coded URL like `http://example.com/favicon.ico`
* If none of the above solutions worked, fall back to the icon found by WebSearch's `_setup_default_icon()` method (current solution)

**Comment by alexandr-san4ez** [comment]
I'll do it somehow. Let the PR remain open.

**Pull request closed without merging**
