### PR TITLE
Add new string plugin casing options

### PR DESCRIPTION
**Pull request by DrorHarari**
Added favorite programmer casing options of lower camel case, upper camel case, snake case and kebab case

### CODE REVIEW

**Comment by polyvertex** [comment]
You made some changes in a different package. I will still merge this PR but please for next time check out the Contribute section of the [README](https://github.com/Keypirinha/Packages/blob/master/README.md) file.

**Comment by DrorHarari** [comment]
Sorry, not too familiar with Git contribution workflow.

Will improve the next time.

>> You made some changes in a different package.
Not sure what is the different package - I think I have sent a PR for the
change to the String plugin of the Packages repo.

/d

**Comment by DrorHarari** [comment]
Oouch, I did not even realize it. I did a change to my repo planning to
send a new PR but shamefully/ignorantly I was working on 'master'. I did
not create a feature branch. I'm a Git newbie - sorry for the confusion.

**Comment by polyvertex** [comment]
Yep, no worries!

**Comment by polyvertex** [comment]
Closing this due to #24

**Pull request closed without merging**
