### PR TITLE
Drorharari/cvt vars

### PR DESCRIPTION
**Pull request by DrorHarari**
This PR includes a complete variable support for Calc (it is much longer than the original 17 lines change). Included:

- Expression ending with :varname will save the result into the variable 'varname' that can be used in further expressions.
- Variables are persisted in the variables.json file under the User folder.
- A Calc Variable command shows existing variable values allowing Copy and Delete actions
- A save_char configuration item allows customizing the character used for saving variables (documented in the calc.ini).

### CODE REVIEW

**Comment by polyvertex** [comment]
Conflicting files put aside, I'm not quite comfortable with the way you implemented it, but I'm fully for having this feature. I also need a bit more time for that alas... :(
For extended discussion: [related issue](https://github.com/Keypirinha/Keypirinha/issues/354).

**Comment by DrorHarari** [comment]
The conflict is because of my reuse of the branch that we discussed (just the credit of the change I made).

Anyway, if you can spell out what you don't like with my implementation and how you would have liked to see it instead, I can make another attempt. Let me know.

BTW, I started playing with a related feature where I double the store character (so >> or ::) with the result being that the variable becomes a vector and then I can get avg/stddev/sum/var/etc.

**Comment by polyvertex** [comment]
I [just answered](https://github.com/Keypirinha/Keypirinha/issues/354). Please continue the discussion there!

**Comment by polyvertex** [comment]
Merged PR #29

**Pull request closed without merging**
